# Generated by Django 3.2.6 on 2021-08-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_remove_subjects_staff_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveReportStudent',
        ),
    ]
