# Generated by Django 3.2.6 on 2021-09-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_delete_leavereportstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationstudent',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='NotificationStaffs',
        ),
        migrations.DeleteModel(
            name='NotificationStudent',
        ),
    ]
