# Generated by Django 3.1.7 on 2021-09-04 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_auto_20210904_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='department_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.departments'),
        ),
    ]
