# Generated by Django 3.2.6 on 2021-09-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_auto_20210903_1924'),
        ('student_management_app', '0016_auto_20210904_1718'),
    ]

    operations = [
    ]
