# Generated by Django 3.1.7 on 2021-09-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0017_intakes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='department_id',
        ),
    ]
