# Generated by Django 3.2.6 on 2021-09-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0017_merge_0010_auto_20210903_1924_0016_auto_20210904_1718'),
        ('student_management_app', '0019_subjects_department_id'),
    ]

    operations = [
    ]
