# Generated by Django 3.1.7 on 2021-09-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_auto_20210903_1924'),
        ('student_management_app', '0019_subjects_department_id'),
    ]

    operations = [
    ]
