# Generated by Django 3.1.7 on 2021-09-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0020_merge_20210907_1242'),
        ('student_management_app', '0020_merge_20210906_2054'),
    ]

    operations = [
    ]
