# Generated by Django 3.1.7 on 2021-09-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0024_auto_20210909_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='semesters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.semesters'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses'),
        ),
    ]
