# Generated by Django 3.1.7 on 2021-09-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0031_auto_20210914_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='session',
        ),
        migrations.AddField(
            model_name='registrations',
            name='semesters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.semesters'),
        ),
    ]
