# Generated by Django 3.2.6 on 2021-09-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0029_attendance_department'),
        ('student_management_app', '0032_auto_20210914_1625'),
    ]

    operations = [
    ]
