# Generated by Django 3.1.7 on 2021-09-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0032_auto_20210914_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='course',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='department',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='registretion_name',
        ),
    ]
