# Generated by Django 3.1.7 on 2021-09-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0033_auto_20210917_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='subject',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
