# Generated by Django 3.2.6 on 2021-09-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0036_alter_attendance_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='medic_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='assignment',
            field=models.BooleanField(default=False),
        ),
    ]
