# Generated by Django 3.2.6 on 2021-10-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0034_auto_20210918_0933'),
        ('student_management_app', '0040_auto_20210921_2027'),
    ]

    operations = [
    ]
