# Generated by Django 3.2.6 on 2021-10-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0041_merge_0034_auto_20210918_0933_0040_auto_20210921_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField()),
                ('title', models.CharField(default='', max_length=100)),
                ('body', models.TextField(default='', max_length=1000)),
                ('points', models.FloatField(default=0.0)),
                ('comments', models.CharField(default='', max_length=200)),
                ('worked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='created',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='questions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='Assignment_submit',
        ),
        migrations.AddField(
            model_name='solution',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.assignment'),
        ),
        migrations.AddField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students'),
        ),
    ]
