# Generated by Django 3.2.6 on 2021-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0042_auto_20211001_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='body',
        ),
        migrations.AddField(
            model_name='solution',
            name='answer',
            field=models.FileField(default='', upload_to='media/questions/answers'),
        ),
    ]
