# Generated by Django 3.1.7 on 2021-10-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0044_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='doc_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
