# Generated by Django 3.1.7 on 2021-10-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0045_auto_20211005_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='docfile',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.docs'),
        ),
    ]
