# Generated by Django 3.1.7 on 2021-10-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0046_auto_20211005_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='answer',
            field=models.FileField(upload_to='%Y/%M/%d'),
        ),
    ]
