# Generated by Django 3.1.7 on 2021-10-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0048_auto_20211005_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='student',
        ),
    ]
