# Generated by Django 3.2.9 on 2021-11-10 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0049_auto_20211005_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='assignment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.docs'),
        ),
    ]
