# Generated by Django 3.2.9 on 2021-11-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0050_solution_assignment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='title',
        ),
        migrations.AddField(
            model_name='solution',
            name='doc_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
    ]
