# Generated by Django 3.2.9 on 2021-11-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0053_auto_20211113_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
