# Generated by Django 3.2.9 on 2021-11-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0055_alter_solution_docfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='docfiles',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
    ]
