# Generated by Django 3.2.9 on 2021-11-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0056_alter_solution_docfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
