# Generated by Django 3.1.7 on 2021-12-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0059_parents_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='parent_password',
        ),
        migrations.RemoveField(
            model_name='students',
            name='parent_password',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student')], default=1, max_length=10),
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
