# Generated by Django 3.2.6 on 2021-09-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_management_app', '0040_auto_20210921_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('assignment_name', models.CharField(max_length=250)),
                ('assignment', models.FileField(upload_to='assignments')),
                ('student', models.ManyToManyField(related_name='student_assignment', to='student_management_app.Students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignment', to='student_management_app.staffs')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('submit', models.FileField(upload_to='Submission')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submit', to='student_management_app.students')),
                ('submitted_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_for_assignment', to='attendance.classassignment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_submit', to='student_management_app.staffs')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageToTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('message_html', models.TextField(editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student_management_app.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='student_management_app.staffs')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'message')},
            },
        ),
        migrations.CreateModel(
            name='ClassNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('message_html', models.TextField(editable=False)),
                ('students', models.ManyToManyField(related_name='class_notice', to='student_management_app.Students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='student_management_app.staffs')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'message')},
            },
        ),
    ]
